name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker image
      run: |
        docker build -t phanuwit13/novel-read-web:${{ github.sha }} .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push phanuwit13/novel-read-web:${{ github.sha }}

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USERNAME }}
        password: ${{ secrets.DO_PASSWORD }}
        script: |
          echo "Deploying image with SHA: ${{ github.sha }}"
          docker pull phanuwit13/novel-read-web:${{ github.sha }}
          docker stop novel-read-web || true
          docker rm novel-read-web || true
          docker run -d --name novel-read-web -p 8001:8080 phanuwit13/novel-read-web:${{ github.sha }}
